### ISSUE TITLE
Programar personagens e artefatos

### ISSUE THREAD

**Issue by fmdo22** [Piermed-Games/Island-Adventure#14]

**Comment by heitorp29** [comment]
Os personagens, Fábio e Heitor, já foram criados. Os artefatos já foram criados também. O personagem Heitor já foi programado em nosso repositório. O personagem Fábio, apesar de já ter sido criado, ainda não foi enviado para o repositório.

Parte principal dos objetos já foram enviados em nosso repositório. Falta algumas que virão mediante as necessidades.

**Comment by fmdo22** [comment]
correção: sem aplicação em jogo de texto
